#ifndef rda_h
#define rda_h 1

#define RDA_HEADER_2_0_MAGIC_LEN 36
#define RDA_HEADER_2_2_MAGIC_LEN 18
#define RDA_HEADER_MAGIC_LEN RDA_HEADER_2_0_MAGIC_LEN

#define RDA_HEADER_2_0_MAGIC "Resource File V2.0"
#define RDA_HEADER_2_2_MAGIC "Resource File V2.2"

#define RDA_HEADER_2_0_PTR_LEN 4
#define RDA_HEADER_2_2_PTR_LEN 8
#define RDA_HEADER_PTR_LEN RDA_HEADER_2_2_PTR_LEN

#define RDA_HEADER_2_0_PTR 1044
#define RDA_HEADER_2_2_PTR 784

#define RDA_VERSION_2_0 0x00
#define RDA_VERSION_2_2 0x01

#endif
